# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source code inside the container
COPY . .

# Expose the port your app is listening on (e.g., 3000)
EXPOSE 3000

# Define the command to run your application
CMD [ "npm", "start" ]
