# Use an official Node.js runtime as the base image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of your application source code into the container
COPY . .

# Build the React app for production
RUN npm run build

# Expose the port your React app will run on (default is 3000)
EXPOSE 3000

# Start the React app
CMD [ "npm", "start" ]
