# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Expose the application port (adjust this to the port your service runs on)
EXPOSE 8000

# Copy the account-service JAR file into the container
COPY target/accounting-service.jar accounting-service.jar

ENTRYPOINT [ "java","-jar", "/accounting-service.jar" ]

