on: [push]

jobs:
  build:
    name: Run springboot-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
              java-version: 1.11
      - uses: education/autograding@v1
